server:
  port: 8088

logging:  level:    org.springframework: DEBUG
    
spring:  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:    user:      name: user
      password: qwe123  jpa:    show-sql: true
    hibernate:      ddl-auto: create
    defer-datasource-initialization: true
    database: h2
  h2:    console:      enabled: true
  datasource:    url: jdbc:h2:mem:testdb
    
      
management:  endpoints:    web:      exposure:        include: "*"
        